---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
platforms:
  - name: omero-public
    image: centos/systemd
    image_version: latest
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
  inventory:
    host_vars:
      omero-public:
        omero_server_systemd_require_network: false
        postgresql_version: "10"
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
