---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
platforms:
  - name: omero-addons
    image: centos/systemd:latest
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
scenario:
  name: centos7
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
